### ISSUE TITLE
Error creating a CRD

### ISSUE THREAD

**Issue by Mexarm** [kubernetes-operators-book/chapters#10]
Hello!

trying to run example in page #14 of the book, executed the command 

```
$ kubectl create -f etcd-operator-crd.yaml
```
and got the error:

```
error: unable to recognize "etcd-operator-crd.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

in kubernetes 1.22 "apiextensions.k8s.io/v1beta1" version was removed 

https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#:~:text=The%20beta%20CustomResourceDefinition%20API%20(apiextensions.k8s.io/v1beta1)

tried to use kubectl convert to convert the manifest to a new version but also getting an error 

```
$ kubectl convert -f etcd-operator-crd.yaml --output-version apiextensions.k8s.io/v1
error: unable to decode "etcd-operator-crd.yaml": no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1" in scheme "pkg/api/legacyscheme/scheme.go:30"
```

any ideas? how to create the CRD in this cluster ?

this is my env:

```
macOS Monterrey
Version 12.3.1

$ oc version
Client Version: openshift-clients-4.5.0-202006231303.p0-21-g297a4ac42
Server Version: 4.10.9
Kubernetes Version: v1.23.5+9ce5071
$ oc whoami  
kubeadmin
```

thanks

**Comment by tznamena** [comment]
I had the same issue, the CRDs have changed (version) and schema is required.
Following changes let me create the CRD, however, I have not verified if these will cause other issues down the road:
```diff
--- a/ch03/etcd-operator-crd.yaml
+++ b/ch03/etcd-operator-crd.yaml
@@ -1,4 +1,4 @@
-apiVersion: apiextensions.k8s.io/v1beta1
+apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
   name: etcdclusters.etcd.database.coreos.com
@@ -13,8 +13,11 @@ spec:
     - etcd
     singular: etcdcluster
   scope: Namespaced
-  version: v1beta2
   versions:
   - name: v1beta2
     served: true
     storage: true
+    schema:
+      openAPIV3Schema:
+        type: object
+        x-kubernetes-preserve-unknown-fields: true


```

**Comment by Mexarm** [comment]
> I had the same issue, the CRDs have changed (version) and schema is required.
> 
> Following changes let me create the CRD, however, I have not verified if these will cause other issues down the road:
> 
> ```diff
> 
> --- a/ch03/etcd-operator-crd.yaml
> 
> +++ b/ch03/etcd-operator-crd.yaml
> 
> @@ -1,4 +1,4 @@
> 
> -apiVersion: apiextensions.k8s.io/v1beta1
> 
> +apiVersion: apiextensions.k8s.io/v1
> 
>  kind: CustomResourceDefinition
> 
>  metadata:
> 
>    name: etcdclusters.etcd.database.coreos.com
> 
> @@ -13,8 +13,11 @@ spec:
> 
>      - etcd
> 
>      singular: etcdcluster
> 
>    scope: Namespaced
> 
> -  version: v1beta2
> 
>    versions:
> 
>    - name: v1beta2
> 
>      served: true
> 
>      storage: true
> 
> +    schema:
> 
> +      openAPIV3Schema:
> 
> +        type: object
> 
> +        x-kubernetes-preserve-unknown-fields: true
> 
> 
> 
> 
> 
> ```

Thanks will give it a try

**Comment by megumish** [comment]
Strictly written, it can also be done this way.

```yaml
...
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              size:
                type: integer
              version:
                type: string
```
