### ISSUE TITLE
Whats is the license? 

### ISSUE THREAD

**Issue by Mazuco** [kubernetes-operators-book/chapters#9]
what would be the license of this repository?

**Comment by joshix** [comment]
Generally: Liberal.

This repository contains the source code from the book _Kubernetes Operators_ by Jason Dobies and Joshua Wood (O’Reilly, 2020). Permission and terms to use, reference, and quote the book's source code are defined in the Preface and reproduced below:

> This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.
>
> We appreciate, but generally do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “Kubernetes Operators by Jason Dobies and Joshua Wood (O’Reilly). Copyright 2020 Red Hat, Inc., 978-1-492-04805-3.”
>
> If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at permissions@oreilly.com.
